# Universal configuration
- import_playbook: base.yml

- name: Install NFS server
  hosts: storage
  become: true
  remote_user: ansible
  roles:
    - role: ansible-role-nfs
      tags: [ansible-role-nfs]

